project:
  type: website
  output-dir: docs

website:
  title: "Xiaoyan Hu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: Research.qmd
        text: "Research"
      - file: Contact.qmd
        text: "Contact Me"
    tools:
      - icon: LinkedIn
        href: www.linkedin.com/in/xiaoyan-hu-b95354114
      - icon: GitHub
        href: https://github.com/xhu41
format:
  html:
    theme: 
     light: lux
     dark: cyborg
    toc: true
    toc-expand: 3
    fontsize: 1em
    css: styles.css

editor: visual

