---
title: "  "
---

## **Research Experience**

I am a PhD Candidate in Public Administration at the University of Illinois at Chicago (UIC), with a concentration on Public Budgeting and Finance. Focusing on fiscal policy at the state and local level, my research mainly examines state budget performance and fiscal conditions.

I have participated in various research projects during my PhD program. In the Volcker Alliance’s Truth and Integrity in State Budgeting project, our research assessed budget practices across the 50 state governments from five perspectives: budget forecasting, budget maneuvers, legacy costs, reserve funds, and budget transparency.

In the Institute of Government and Public Affairs’ Fiscal Futures project, our analyses provide information to the Illinois public and policymakers about the state’s budget performance and fiscal condition. Meanwhile, the Fiscal Futures team collaborated on various projects, including studies of the flat vs. graduated income tax systems, the unemployment insurance trust fund, and the influence of remote work.

To increase the scope of my research activities, I have also participated in several research groups. For example, in a survey research group at UIC, one of our ongoing project is a manuscript using experimental vignettes to explore factors influencing the public’s evaluation of opinion polls. Recently we have been working on a project using information from the 2022 General Social Survey, and we have proposed a three-item scale to measure the survey taking climate.

Currently, I am revising my dissertation, which employs a three-essay format to study the diffusion of budget stabilization funds (BSFs) among U.S. states. Using an event history analysis approach, the first study examines the diffusion mechanism for BSFs. The second study conducts a text analysis to explore BSFs’ potential reinvention over time. Finally, the third study hypothesized a federal-level BSF and provides a policy simulation to justify its fiscal feasibility.
